var animales = [
  "Perro",
  "Gato",
  "Elefante",
  "León",
  "Tigre",
  "Oso",
  "Mono",
  "Cebra",
  "Jirafa",
  "Caballo",
  "Vaca",
  "Conejo",
  "Lobo",
  "Ratón",
  "Murciélago",
  "Serpiente",
  "Araña",
  "Cocodrilo",
  "Hipopótamo",
  "Delfín",
  "Tortuga",
  "Pingüino",
  "Pato",
  "Gorila",
  "Pez",
  "Avestruz",
  "Camello",
  "Hormiga",
  "Abeja",
  "Colibrí",
];

var sustantivos = [
  "Luz",
  "Mesa",
  "Carro",
  "Llave",
  "Lago",
  "Taza",
  "Pan",
  "Cama",
  "Silla",
  "Puerta",
  "Tierra",
  "Árbol",
  "Nube",
  "Montaña",
  "Bosque",
  "Lápiz",
  "Banco",
  "Camino",
  "Flor",
  "Libro",
  "Río",
  "Reloj",
  "Mango",
  "Naranja",
  "Limon",
  "Nieve",
  "Sauce",
  "Madera",
  "Oro",
  "Plata",
  "Cobre",
  "Hierro",
  "Cielo",
  "Estrella",
  "Mariposa",
  "Caramelo",
  "Helado",
  "Abuela",
  "Pantalón",
  "Camisa",
  "Botella",
];

var musicos = [
  "Taylor Swift",
  "Ed Sheeran",
  "Beyoncé",
  "Drake",
  "Adele",
  "Rihanna",
  "Eminem",
  "Justin Bieber",
  "Bruno Mars",
  "Katy Perry",
  "The Weeknd",
  "Ariana Grande",
  "Coldplay",
  "Maroon 5",
  "Kendrick Lamar",
  "Post Malone",
  "Lady Gaga",
  "Billie Eilish",
  "Imagine Dragons",
  "Shawn Mendes",
  "Sia",
  "Nicki Minaj",
  "U2",
  "Queen",
  "Michael Jackson",
  "Madonna",
  "Prince",
  "Elton John",
  "Whitney Houston",
  "Stevie Wonder",
  "Bob Dylan",
  "David Bowie",
  "The Rolling Stones",
  "AC/DC",
  "Metallica",
  "Nirvana",
  "Guns N' Roses",
  "Pink Floyd",
  "Led Zeppelin",
  "The Beatles",
  "The Who",
  "Radiohead",
  "Red Hot Chili Peppers",
  "Linkin Park",
  "Oasis",
  "Blur",
  "Arctic Monkeys",
  "Muse",
  "Green Day",
  "Paramore",
  "Foo Fighters",
  "Twenty One Pilots",
  "Lana Del Rey",
  "SZA",
  "Dua Lipa",
  "Cardi B",
  "Travis Scott",
  "Kanye West",
  "Jay-Z",
  "Snoop Dogg",
  "Dr. Dre",
  "Lil Wayne",
  "Eminem",
  "Post Malone",
  "J. Cole",
  "Kendrick Lamar",
  "Chance the Rapper",
  "Childish Gambino",
  "Future",
  "The Weeknd",
  "Frank Ocean",
  "Tyler, The Creator",
  "Anderson .Paak",
  "Solange",
  "Migos",
  "Beyoncé",
  "Rihanna",
  "Alicia Keys",
  "Janelle Monáe",
  "Lizzo",
  "Bruno Mars",
  "John Legend",
  "Justin Timberlake",
  "Chris Brown",
  "Jason Derulo",
  "Pitbull",
  "Shakira",
  "Selena Gomez",
  "Demi Lovato",
  "Ariana Grande",
  "Camila Cabello",
  "Billie Eilish",
  "Sia",
  "Halsey",
  "Zayn Malik",
  "Harry Styles",
  "Sam Smith",
  "Charlie Puth",
  "Shawn Mendes",
  "The Chainsmokers",
  "Marshmello",
  "Calvin Harris",
  "Martin Garrix",
  "Kygo",
  "Avicii",
  "David Guetta",
  "Tiësto",
];

var peliculas = [
  "El Padrino",
  "Pulp Fiction",
  "El Señor de los Anillos",
  "El Caballero de la Noche",
  "La Lista de Schindler",
  "El Bueno, el Malo y el Feo",
  "Forrest Gump",
  "Origen",
  "El Club de la Pelea",
  "Ciudadano Kane",
  "El Resplandor",
  "Matrix",
  "Titanic",
  "Interestelar",
  "La Vida es Bella",
  "Gladiador",
  "La Naranja Mecánica",
  "El Silencio de los Inocentes",
  "El Gran Dictador",
  "El Laberinto del Fauno",
  "El Hombre Araña",
  "Star Wars",
  "Volver al Futuro",
  "El Rey León",
  "Los Siete Magníficos",
  "El Exorcista",
  "El Discurso del Rey",
  "El Viaje de Chihiro",
  "La Bella y la Bestia",
  "El Secreto de sus Ojos",
  "El Cisne Negro",
  "La Princesa Mononoke",
  "El Último Tango en París",
  "El Pianista",
  "Psicosis",
  "La La Land",
  "El Código Da Vinci",
  "El Sexto Sentido",
  "Jurassic Park",
  "El Club de los Poetas Muertos",
  "El Hombre Bicentenario",
  "El Mago de Oz",
  "El Cazador de Sueños",
  "El Buen Mentiroso",
  "El Lado Bueno de las Cosas",
  "El Origen del Planeta de los Simios",
  "El Último Samurai",
  "El Gran Hotel Budapest",
  "El Castillo Ambulante",
  "El Gran Gatsby",
  "El Juego de la Imitación",
  "El Informante",
];

var sentimientos = [
  "Alegría",
  "Tristeza",
  "Amor",
  "Odio",
  "Felicidad",
  "Miedo",
  "Esperanza",
  "Ira",
  "Culpabilidad",
  "Enojo",
  "Dolor",
  "Emoción",
  "Sorpresa",
  "Euforia",
  "Nostalgia",
  "Satisfacción",
  "Vergüenza",
  "Envidia",
  "Asco",
  "Confusión",
  "Gratitud",
  "Inseguridad",
  "Preocupación",
  "Aversión",
  "Empatía",
  "Cariño",
  "Paz",
  "Sosiego",
  "Admiración",
  "Culpa",
  "Esperanza",
];

var adjetivos = [
  "Alegre",
  "Triste",
  "Amoroso",
  "Odioso",
  "Feliz",
  "Aterrado",
  "Esperanzado",
  "Irritado",
  "Culpable",
  "Enojado",
  "Doloroso",
  "Emocionante",
  "Sorprendente",
  "Eufórico",
  "Nostálgico",
  "Satisfecho",
  "Vergonzoso",
  "Envidioso",
  "Asqueroso",
  "Confuso",
  "Agradecido",
  "Inseguro",
  "Preocupado",
  "Aversivo",
  "Empático",
  "Cariñoso",
  "Pacífico",
  "Tranquilo",
  "Admirable",
  "Culpable",
  "Esperanzado",
];

var palabrasCion = [
  "Acción",
  "Reacción",
  "Adopción",
  "Corrupción",
  "Educación",
  "Inspiración",
  "Conversación",
  "Obligación",
  "Investigación",
  "Colaboración",
  "Producción",
  "Dirección",
  "Expansión",
  "Preservación",
  "Evaluación",
  "Reflexión",
  "Innovación",
  "Transición",
  "Declaración",
  "Negociación",
];

var palabrasIa = [
  "fantasía",
  "historia",
  "geografía",
  "economía",
  "poesía",
  "biología",
  "psicología",
  "teoría",
  "melodía",
  "astronomía",
  "familia",
  "galería",
  "academia",
  "armonía",
  "auditoría",
  "democracia",
  "tecnología",
  "farmacia",
  "utopía",
  "geometría",
  "sinfonía",
  "fotografía",
  "emoción",
  "rebelión",
  "naturaleza",
  "religión",
  "historiografía",
  "provincia",
  "fantasía",
  "euforia",
  "distancia",
];

var palabrasIo = [
  "servicio",
  "directorio",
  "comercio",
  "negocio",
  "folio",
  "medio",
  "anuncio",
  "desafío",
  "convenio",
  "repositorio",
  "inicio",
  "testimonio",
  "desperdicio",
  "religio",
  "beneficio",
  "desafío",
  "ejercicio",
  "presidio",
  "inventario",
  "principio",
  "desafío",
  "ejemplario",
  "equilibrio",
  "criterio",
  "compartimiento",
  "albedrío",
  "episodio",
  "beneficiario",
  "envío",
  "desperdicio",
];

var palabras = [
  "grande",
  "feliz",
  "caliente",
  "rápido",
  "luminoso",
  "alto",
  "bueno",
  "amable",
  "valiente",
  "sabroso",
  "alegre",
  "amor",
  "nuevo",
  "limpio",
  "claro",
  "fácil",
  "dulce",
  "interesante",
  "fuerte",
  "positivo",
];

var antonimos = [
  "pequeño",
  "triste",
  "frío",
  "lento",
  "oscuro",
  "bajo",
  "malo",
  "grosero",
  "cobarde",
  "insípido",
  "triste",
  "odio",
  "viejo",
  "sucio",
  "oscuro",
  "difícil",
  "amargo",
  "aburrido",
  "débil",
  "negativo",
];

const wordBankList = [
  sentimientos,
  musicos,
  sentimientos,
  palabrasIa,
  palabrasIo,
  palabras,
  adjetivos,
  antonimos,
  animales,
  palabrasCion,
  sustantivos,
  adjetivos,
  sustantivos,
  sentimientos,
  peliculas,
  antonimos,
  palabras,
  sustantivos,
  palabrasIo,
  animales,
  palabrasIa,
  sustantivos,
  adjetivos,
  sentimientos,
  palabrasCion,
  sentimientos,
  sustantivos,
  palabras,
  palabrasCion,
  adjetivos,
  antonimos,
  palabrasIa,
  palabrasIo,
];

export function getRandomWordFromArray() {
  const randomSet =
    wordBankList[Math.floor(Math.random() * wordBankList.length)];
  const randomIndex = Math.floor(Math.random() * randomSet.length);
  return randomSet[randomIndex];
}

export default getRandomWordFromArray;
