const adjetivos = [
  "audaz",
  "brillante",
  "frenético",
  "poderoso",
  "explosivo",
  "atrevido",
  "feroz",
  "inspirador",
  "incansable",
  "intenso",
  "valiente",
  "sorprendente",
  "ardiente",
  "letal",
  "único",
  "imparable",
  "salvaje",
  "atrevido",
  "imponente",
  "radiante",
  "astuto",
  "deslumbrante",
  "soberbio",
  "versátil",
  "feroz",
  "arriesgado",
  "triunfante",
  "bravo",
  "espectacular",
  "improvisado",
];

const sustantivos = [
  "fuego",
  "destino",
  "guerrero",
  "sueño",
  "rebeldía",
  "estrella",
  "corazón",
  "luz",
  "batalla",
  "victoria",
  "fuerza",
  "alma",
  "orgullo",
  "esperanza",
  "magia",
  "sangre",
  "poder",
  "ritmo",
  "libertad",
  "locura",
  "destreza",
  "resistencia",
  "vida",
  "trueno",
  "pasión",
  "gloria",
  "inspiración",
  "leyenda",
  "conquista",
  "sacrificio",
];

const verbos = [
  "improvisar",
  "conquistar",
  "sorprender",
  "dominar",
  "innovar",
  "inspirar",
  "desafiar",
  "crear",
  "destacar",
  "enfrentar",
  "transformar",
  "brillar",
  "perseguir",
  "elevar",
  "deslumbrar",
  "romper",
  "resistir",
  "vencer",
  "avanzar",
  "arrojar",
  "apoderarse",
  "despertar",
  "triunfar",
  "incendiar",
  "soñar",
  "rebeldar",
  "estallar",
  "impactar",
  "liberar",
  "revolucionar",
];

const cine = [
  "acción",
  "aventura",
  "drama",
  "comedia",
  "suspenso",
  "terror",
  "romance",
  "ciencia ficción",
  "fantasía",
  "thriller",
  "director",
  "actor",
  "actriz",
  "guion",
  "escena",
  "pantalla",
  "estreno",
  "secuela",
  "reparto",
  "efectos especiales",
  "banda sonora",
  "cámara",
  "montaje",
  "trama",
  "premio",
  "taquilla",
  "guión",
  "cineasta",
  "producción",
  "galardón",
  "proyección",
];

const emociones = [
  "alegría",
  "tristeza",
  "ira",
  "amor",
  "odio",
  "esperanza",
  "miedo",
  "sorpresa",
  "ansiedad",
  "felicidad",
  "nostalgia",
  "desesperación",
  "celos",
  "empatía",
  "euforia",
  "vergüenza",
  "entusiasmo",
  "paz",
  "frustración",
  "confianza",
  "inseguridad",
  "gratitud",
  "satisfacción",
  "ternura",
  "admiración",
  "desilusión",
  "preocupación",
  "ternura",
  "alivio",
  "desesperanza",
];

const valores = [
  "amistad",
  "honestidad",
  "respeto",
  "solidaridad",
  "justicia",
  "tolerancia",
  "generosidad",
  "paciencia",
  "superación",
  "compromiso",
  "humildad",
  "integridad",
  "perseverancia",
  "igualdad",
  "libertad",
  "sinceridad",
  "lealtad",
  "empatía",
  "bondad",
  "responsabilidad",
  "gratitud",
  "humor",
  "sabiduría",
  "creatividad",
  "optimismo",
  "afecto",
  "valentía",
  "compasión",
  "autenticidad",
  "cooperación",
  "firmeza",
];

const profesiones = [
  "médico",
  "ingeniero",
  "abogado",
  "profesor",
  "arquitecto",
  "músico",
  "escritor",
  "actor",
  "pintor",
  "bombero",
  "policía",
  "chef",
  "periodista",
  "científico",
  "atleta",
  "cantante",
  "diseñador",
  "fotógrafo",
  "programador",
  "empresario",
  "psicólogo",
  "astronauta",
  "cirujano",
  "piloto",
  "veterinario",
  "agricultor",
  "economista",
  "electricista",
  "enfermero",
  "fontanero",
];

const comida = [
  "pizza",
  "hamburguesa",
  "sushi",
  "tacos",
  "ensalada",
  "pollo",
  "pasta",
  "sandwich",
  "queso",
  "pan",
  "arroz",
  "fresas",
  "helado",
  "pastel",
  "chocolate",
  "caramelo",
  "patatas",
  "maíz",
  "salchicha",
  "pescado",
  "camarones",
  "burrito",
  "huevo",
  "yogur",
  "uvas",
  "manzana",
  "naranja",
  "zanahoria",
  "pepino",
  "pimiento",
];

const paises = [
  "España",
  "México",
  "Argentina",
  "Colombia",
  "Perú",
  "Chile",
  "Brasil",
  "Estados Unidos",
  "Canadá",
  "Francia",
  "Alemania",
  "Italia",
  "China",
  "Japón",
  "Corea del Sur",
  "Australia",
  "Rusia",
  "India",
  "Egipto",
  "Sudáfrica",
  "Marruecos",
  "Inglaterra",
  "Portugal",
  "Holanda",
  "Suecia",
  "Noruega",
  "Grecia",
  "Turquía",
  "Israel",
  "Arabia Saudita",
];

const marcas = [
  "Nike",
  "Adidas",
  "Apple",
  "Coca-Cola",
  "Samsung",
  "Amazon",
  "Microsoft",
  "Google",
  "McDonald's",
  "Sony",
  "Puma",
  "Volkswagen",
  "Toyota",
  "Gucci",
  "Louis Vuitton",
  "H&M",
  "Zara",
  "Nike",
  "Rolex",
  "Ferrari",
  "Chanel",
  "L'Oréal",
  "Nestlé",
  "Pepsi",
  "Prada",
  "IKEA",
  "Starbucks",
  "Lacoste",
  "Levi's",
  "Mercedes-Benz",
];

const frutas = [
  "manzana",
  "plátano",
  "naranja",
  "sandía",
  "uva",
  "fresa",
  "piña",
  "mango",
  "kiwi",
  "limón",
  "papaya",
  "melón",
  "pera",
  "cereza",
  "mandarina",
  "coco",
  "frambuesa",
  "granada",
  "melocotón",
  "maracuyá",
  "guayaba",
  "ciruela",
  "higo",
  "zarzamora",
  "guanábana",
  "mora",
  "caqui",
  "litchi",
  "mangostán",
  "caña de azúcar",
];

const animales = [
  "perro",
  "gato",
  "león",
  "elefante",
  "tigre",
  "jirafa",
  "serpiente",
  "cocodrilo",
  "águila",
  "pingüino",
  "ballena",
  "mono",
  "oso",
  "vaca",
  "cabra",
  "cebra",
  "lobo",
  "rinoceronte",
  "camello",
  "tortuga",
  "murciélago",
  "gallina",
  "hormiga",
  "araña",
  "abeja",
  "delfín",
  "hipopótamo",
  "gorila",
  "colibrí",
  "mariposa",
];

const verduras = [
  "zanahoria",
  "brócoli",
  "espinaca",
  "cebolla",
  "pepino",
  "tomate",
  "pimiento",
  "lechuga",
  "calabacín",
  "remolacha",
  "col",
  "apio",
  "alcachofa",
  "espárrago",
  "judía verde",
  "berenjena",
  "rúcula",
  "coliflor",
  "puerro",
  "repollo",
  "calabaza",
  "habas",
  "acelga",
  "champiñón",
  "nabo",
  "perejil",
  "rábano",
  "calabaza",
  "endibia",
  "calabaza",
];

const instrumentos = [
  "guitarra",
  "piano",
  "batería",
  "violín",
  "flauta",
  "saxofón",
  "trompeta",
  "bajo",
  "trombón",
  "acordeón",
  "arpa",
  "ukelele",
  "clarinete",
  "órgano",
  "cítara",
  "viola",
  "sitar",
  "teclado",
  "xilófono",
  "didgeridoo",
  "tuba",
  "gaita",
  "marimba",
  "corno",
  "melódica",
  "espineta",
  "timple",
  "theremin",
  "bansuri",
  "djembe",
];

const historia = [
  "civilización",
  "imperio",
  "revolución",
  "batalla",
  "conquista",
  "descubrimiento",
  "reforma",
  "independencia",
  "revolución industrial",
  "guerra",
  "dinastía",
  "dictadura",
  "renacimiento",
  "monarquía",
  "colonia",
  "imperialismo",
  "edad media",
  "edad moderna",
  "edad contemporánea",
  "prehistoria",
  "antiguo Egipto",
  "imperio romano",
  "Edad de los Descubrimientos",
  "Revolución Francesa",
  "Revolución Rusa",
  "Guerra Mundial",
  "Revolución Industrial",
  "inquisición",
  "imperio bizantino",
  "guerra civil",
  "conquista de América",
];

const sociedad = [
  "igualdad",
  "diversidad",
  "justicia",
  "libertad",
  "derechos",
  "inclusión",
  "solidaridad",
  "tolerancia",
  "empoderamiento",
  "equidad",
  "cambio",
  "educación",
  "compromiso",
  "respeto",
  "violencia",
  "discriminación",
  "pobreza",
  "corrupción",
  "medio ambiente",
  "migración",
  "derechos humanos",
  "desigualdad",
  "participación",
  "cooperación",
  "sostenibilidad",
  "progreso",
  "transformación",
  "conciencia",
  "construcción social",
  "pluralismo",
];

const educacion = [
  "aprendizaje",
  "maestro",
  "estudiante",
  "conocimiento",
  "escuela",
  "universidad",
  "clase",
  "lectura",
  "escritura",
  "matemáticas",
  "ciencia",
  "historia",
  "geografía",
  "arte",
  "música",
  "deporte",
  "investigación",
  "laboratorio",
  "examen",
  "proyecto",
  "creatividad",
  "enseñanza",
  "tutoría",
  "tecnología educativa",
  "carrera",
  "diploma",
  "desarrollo personal",
  "educación inclusiva",
  "alfabetización",
  "disciplina",
];

const salud = [
  "salud",
  "bienestar",
  "enfermedad",
  "prevención",
  "medicina",
  "hospital",
  "médico",
  "enfermero",
  "paciente",
  "tratamiento",
  "nutrición",
  "ejercicio",
  "mente",
  "cuerpo",
  "equilibrio",
  "resiliencia",
  "físico",
  "mental",
  "emocional",
  "saludable",
  "vida",
  "cuidado",
  "hábitos",
  "prevención",
  "vacuna",
  "diagnóstico",
  "rehabilitación",
  "sueño",
  "estrés",
  "relajación",
];

const tecnologia = [
  "innovación",
  "computadora",
  "teléfono",
  "internet",
  "redes sociales",
  "software",
  "hardware",
  "aplicación",
  "inteligencia artificial",
  "realidad virtual",
  "ciberseguridad",
  "datos",
  "programación",
  "nube",
  "robot",
  "smartphone",
  "tableta",
  "inteligente",
  "conectividad",
  "intuitivo",
  "digital",
  "tecnológico",
  "dispositivo",
  "autónomo",
  "código",
  "tecnología wearable",
  "Internet de las cosas",
  "ciberespacio",
  "inteligencia de datos",
  "cifrado",
  "realidad aumentada",
];

const ciencia = [
  "investigación",
  "experimento",
  "teoría",
  "descubrimiento",
  "laboratorio",
  "química",
  "física",
  "biología",
  "astronomía",
  "genética",
  "evolución",
  "célula",
  "partícula",
  "materia",
  "energía",
  "ecología",
  "medicina",
  "neurociencia",
  "geología",
  "microscopio",
  "ADN",
  "cambio climático",
  "espacio",
  "ecosistema",
  "biotecnología",
  "holograma",
  "robot",
  "clonación",
  "vacuna",
  "sostenibilidad",
];

const literatura = [
  "poesía",
  "novela",
  "cuento",
  "drama",
  "verso",
  "prosa",
  "autor",
  "escritor",
  "lector",
  "libro",
  "personaje",
  "trama",
  "fantasía",
  "realismo",
  "surrealismo",
  "romanticismo",
  "modernismo",
  "clásico",
  "épico",
  "metáfora",
  "rima",
  "estilo",
  "estructura",
  "narrativa",
  "poeta",
  "figura retórica",
  "ironía",
  "simbolismo",
  "literatura universal",
  "literatura contemporánea",
];

const entretenimiento = [
  "música",
  "cine",
  "teatro",
  "televisión",
  "videojuegos",
  "deporte",
  "espectáculo",
  "concierto",
  "festival",
  "arte",
  "baile",
  "comedia",
  "drama",
  "acción",
  "aventura",
  "suspenso",
  "juego",
  "diversión",
  "risa",
  "emoción",
  "magia",
  "acrobatas",
  "malabarismo",
  "circo",
  "maratón",
  "competencia",
  "espectador",
  "artista",
  "actor",
  "músico",
  "coreografía",
];

const biologia = [
  "célula",
  "ADN",
  "genética",
  "evolución",
  "especie",
  "organismo",
  "microorganismo",
  "reproducción",
  "herencia",
  "mutación",
  "ecosistema",
  "biodiversidad",
  "biotecnología",
  "metabolismo",
  "mitosis",
  "meiosis",
  "biología molecular",
  "fotosíntesis",
  "respiración",
  "homeostasis",
  "tejido",
  "órgano",
  "sistema",
  "hormona",
  "neurona",
  "enzima",
  "virus",
  "bacteria",
  "ecología",
  "nutrición",
];

const quimica = [
  "elemento",
  "compuesto",
  "reacción",
  "átomo",
  "molécula",
  "tabla periódica",
  "enlace",
  "reactivo",
  "producto",
  "equilibrio",
  "ácido",
  "base",
  "pH",
  "catalizador",
  "estructura",
  "propiedad",
  "termoquímica",
  "electrón",
  "ion",
  "oxidación",
  "reducción",
  "estequiometría",
  "energía de activación",
  "equación química",
  "isótopo",
  "radioactividad",
  "química orgánica",
  "química inorgánica",
  "química analítica",
  "química física",
  "química ambiental",
];

const fisica = [
  "energía",
  "movimiento",
  "fuerza",
  "velocidad",
  "aceleración",
  "gravedad",
  "masa",
  "momento",
  "trabajo",
  "potencia",
  "ley",
  "campo",
  "partícula",
  "electromagnetismo",
  "electricidad",
  "magnetismo",
  "óptica",
  "sonido",
  "ondas",
  "radiación",
  "termodinámica",
  "termodinámica",
  "presión",
  "carga",
  "ley de Newton",
  "ley de Ohm",
  "ley de Coulomb",
  "relatividad",
];

const deportes = [
  "fútbol",
  "baloncesto",
  "tenis",
  "natación",
  "atletismo",
  "ciclismo",
  "gimnasia",
  "béisbol",
  "voleibol",
  "boxeo",
  "golf",
  "rugby",
  "surf",
  "esquí",
  "snowboard",
  "karate",
  "judo",
  "hockey",
  "patinaje",
  "escalada",
  "parkour",
  "lucha libre",
  "taekwondo",
  "paddle surf",
  "equitación",
  "bádminton",
  "ajedrez",
  "yoga",
  "pilates",
  "triatlón",
];

const wordCategories = [
  "adjetivos",
  "sustantivos",
  "verbos",
  "cine",
  "emociones",
  "valores",
  "profesiones",
  "comida",
  "paises",
  "marcas",
  "frutas",
  "animales",
  "verduras",
  "instrumentos",
  "historia",
  "sociedad",
  "educacion",
  "salud",
  "tecnologia",
  "ciencia",
  "literatura",
  "entretenimiento",
  "biologia",
  "quimica",
  "fisica",
  "deportes",
];

const wordBankList = {
  adjetivos,
  sustantivos,
  verbos,
  cine,
  emociones,
  valores,
  profesiones,
  comida,
  paises,
  marcas,
  frutas,
  animales,
  verduras,
  instrumentos,
  historia,
  sociedad,
  educacion,
  salud,
  tecnologia,
  ciencia,
  literatura,
  entretenimiento,
  biologia,
  quimica,
  fisica,
  deportes,
};

const ito = [
  "mito",
  "escrito",
  "distrito",
  "delito",
  "quito",
  "grito",
  "requisito",
  "benito",
  "circuito",
  "infinito",
  "manuscrito",
  "descrito",
  "suscrito",
  "rito",
  "repito",
  "necesito",
  "gratuito",
  "bonito",
  "erudito",
  "apetito",
  "inscrito",
  "bonito",
  "hito",
  "poquito",
  "granito",
  "favorito",
  "permito",
  "maldito",
  "exquisito",
  "solicito",
  "finito",
  "fortuito",
  "remito",
  "prescrito",
  "bendito",
  "chiquito",
  "invito",
  "felicito",
  "mosquito",
  "pito",
  "inaudito",
  "grafito",
  "admito",
  "ditto",
  "señorito",
  "limito",
  "frito",
  "ratito",
  "monolito",
];

const ina = [
  "mina",
  "fina",
  "domina",
  "colina",
  "tina",
  "cantina",
  "sabrina",
  "ketamina",
  "argentina",
  "latina",
  "doctrina",
  "oficina",
  "medicina",
  "marina",
  "disciplina",
  "china",
  "termina",
  "determina",
  "divina",
  "femenina",
  "campesina",
  "cocina",
  "esquina",
  "denomina",
  "harina",
  "ruina",
  "origina",
  "masculina",
  "vecina",
  "rutina",
  "predomina",
  "opina",
  "gasolina",
  "examina",
  "cortina",
  "camina",
  "elimina",
  "culmina",
  "proteína",
  "vitamina",
  "gallina",
  "inclina",
  "palestina",
  "espina",
  "combina",
  "orina",
  "destina",
  "cocaína",
  "ilumina",
  "imagina",
  "genuina",
  "paulatina",
  "clandestina",
  "heroína",
  "sobrina",
  "repentina",
  "piscina",
  "cabina",
  "resina",
  "insulina",
  "retina",
  "adivina",
  "neblina",
  "cristalina",
  "coordina",
  "vagina",
  "penicilina",
  "bailarina",
  "sardina",
];

const ero = [
  "cero",
  "sincero",
  "aguacero",
  "pero",
  "primero",
  "enero",
  "febrero",
  "dinero",
  "verdadero",
  "quiero",
  "extranjero",
  "tercero",
  "financiero",
  "obrero",
  "caballero",
  "guerrero",
  "ingeniero",
  "entero",
  "acero",
  "mero",
  "espero",
  "cuero",
  "considero",
  "consejero",
  "heredero",
  "sombrero",
  "viajero",
  "tesorero",
  "cordero",
  "prisionero",
  "ligero",
  "severo",
  "sendero",
  "misionero",
  "suero",
  "prefiero",
  "crucero",
  "agujero",
  "tablero",
  "pasajero",
  "mensajero",
  "soltero",
  "portero",
  "carpintero",
  "marinero",
  "esmero",
  "pionero",
  "paradero",
  "barbero",
  "vocero",
  "aventurero",
  "duradero",
  "torero",
  "carnero",
  "potrero",
  "vivero",
  "reportero",
  "certero",
  "trasero",
  "fichero",
];

const oso = [
  "oso",
  "religioso",
  "famoso",
  "poderoso",
  "curioso",
  "esposo",
  "hermoso",
  "peligroso",
  "valioso",
  "reposo",
  "maravilloso",
  "nervioso",
  "generoso",
  "riguroso",
  "mentiroso",
  "doloroso",
  "glorioso",
  "forzoso",
  "precioso",
  "luminoso",
  "amoroso",
  "ambicioso",
  "orgulloso",
  "silencioso",
  "cuidadoso",
  "novedoso",
  "costoso",
  "celoso",
  "sospechoso",
  "respetuoso",
  "gracioso",
  "exitoso",
  "furioso",
  "acoso",
  "virtuoso",
  "piadoso",
  "prestigioso",
  "ingenioso",
  "espantoso",
  "asombroso",
  "temeroso",
  "ansioso",
  "delicioso",
  "ocioso",
  "mounstroso",
  "dichoso",
  "ventajoso",
  "escandaloso",
  "fabuloso",
  "amistoso",
  "cariñoso",
  "foso",
  "gozo",
  "calabozo",
  "destrozo",
  "trozo",
  "mozo",
  "sollozo",
  "rozo",
  "pozo",
];

const ano = [
  "vano",
  "mano",
  "humano",
  "hermano",
  "verano",
  "temprano",
  "grano",
  "sano",
  "fulano",
  "urano",
  "propano",
  "mexicano",
  "plano",
  "urbano",
  "ciudadano",
  "americano",
  "cristiano",
  "soberano",
  "cubano",
  "cercano",
  "mediano",
  "hispano",
  "lejano",
  "llano",
  "piano",
  "anciano",
  "vaticano",
  "antemano",
  "tirano",
  "cirujano",
  "banano",
  "artesano",
  "paisano",
  "meridiano",
  "guano",
  "veterano",
  "gusano",
  "profano",
  "pagano",
  "pantano",
  "gitano",
  "enano",
  "liviano",
  "soprano",
  "villano",
  "mundano",
  "aldeano",
  "marciano",
  "metano",
  "aeroplano",
  "troyano",
  "marrano",
  "habano",
  "insano",
];

const ido = [
  "sentido",
  "perdido",
  "querido",
  "parecido",
  "olvido",
  "vivido",
  "vestido",
  "desaparecido",
  "vencido",
  "herido",
  "crecido",
  "prohibido",
  "dormido",
  "sorprendido",
  "repetido",
  "encendido",
  "bienvenido",
  "arrepentido",
  "deprimido",
  "cupido",
  "rugido",
  "sido",
  "ido",
  "partido",
  "debido",
  "tenido",
  "contenido",
  "podido",
  "conocido",
  "establecido",
  "recibido",
  "producido",
  "nacido",
  "marido",
  "reducido",
  "unido",
  "dirigido",
  "elegido",
  "oido",
  "cumplido",
  "pedido",
  "recorrido",
  "sonido",
  "ruido",
  "tejido",
  "detenido",
  "leido",
  "incluido",
  "mantenido",
  "caído",
  "apellido",
  "traído",
  "dividido",
  "pido",
  "aprendido",
  "comprometido",
  "traducido",
  "concluido",
  "creído",
  "despido",
  "fallecido",
  "ejido",
  "invertido",
];

const igo = [
  "amigo",
  "enemigo",
  "trigo",
  "testigo",
  "conmigo",
  "castigo",
  "contigo",
  "abrigo",
  "ombligo",
  "mendigo",
  "bendigo",
  "maldigo",
  "prosigo",
  "digo",
  "sigo",
  "higo",
  "persigo",
  "contradigo",
];

const ivo = [
  "objetivo",
  "ejecutivo",
  "motivo",
  "archivo",
  "cultivo",
  "relativo",
  "activo",
  "efectivo",
  "vivo",
  "colectivo",
  "educativo",
  "positivo",
  "productivo",
  "negativo",
  "definitivo",
  "decisivo",
  "pasivo",
  "exclusivo",
  "primitivo",
  "recibo",
  "directivo",
  "atractivo",
  "excesivo",
  "progresivo",
  "operativo",
  "subjetivo",
  "dispositivo",
  "normativo",
  "sucesivo",
  "informativo",
  "sustantivo",
  "escribo",
  "masivo",
  "deportivo",
  "creativo",
  "alternativo",
  "expresivo",
  "cooperativo",
  "incentivo",
  "distintivo",
  "agresivo",
  "preventivo",
  "exhaustivo",
  "afectivo",
  "corporativo",
  "equitativo",
  "reflexivo",
  "selectivo",
  "cautivo",
  "festivo",
  "defensivo",
  "cognitivo",
  "explosivos",
  "emotivo",
  "llamativo",
  "decorativo",
  "intuitivo",
  "fugitivo",
  "chivo",
  "expansivo",
  "apelativo",
  "televisivo",
  "abusivo",
  "ofensivo",
  "nocivo",
  "lucrativo",
  "obsesivo",
  "compulsivo",
];

const terminacionesList = [
  "ito",
  "ina",
  "ero",
  "oso",
  "ano",
  "ido",
  "igo",
  "ivo",
];

const terminaciones = { ito, ina, ero, oso, ano, ido, igo, ivo };

const images = [
  "https://fsivvquhttqtxpvvfyla.supabase.co/storage/v1/object/public/images/image1.jpg",
  "https://fsivvquhttqtxpvvfyla.supabase.co/storage/v1/object/public/images/image2.jpg",
  "https://fsivvquhttqtxpvvfyla.supabase.co/storage/v1/object/public/images/image3.jpg",
  "https://fsivvquhttqtxpvvfyla.supabase.co/storage/v1/object/public/images/image4.jpg",
  "https://fsivvquhttqtxpvvfyla.supabase.co/storage/v1/object/public/images/image5.jpg",
  "https://fsivvquhttqtxpvvfyla.supabase.co/storage/v1/object/public/images/image6.jpg",
  "https://fsivvquhttqtxpvvfyla.supabase.co/storage/v1/object/public/images/image7.jpg",
  "https://fsivvquhttqtxpvvfyla.supabase.co/storage/v1/object/public/images/image8.jpg",
  "https://fsivvquhttqtxpvvfyla.supabase.co/storage/v1/object/public/images/image9.jpg",
  "https://fsivvquhttqtxpvvfyla.supabase.co/storage/v1/object/public/images/image10.jpg",
  "https://fsivvquhttqtxpvvfyla.supabase.co/storage/v1/object/public/images/image11.jpg",
];

export function getRandomFourFromArray(fourCategory) {
  const categorySet = terminaciones[fourCategory];
  const randomFour = categorySet.sort(() => 0.5 - Math.random()).slice(0, 4);
  return randomFour;
}

export function getRandomFourCategory() {
  const randomIndex = Math.floor(Math.random() * terminacionesList.length);
  return terminacionesList[randomIndex];
}

export function getRandomWordFromArray(category) {
  const categorySet = wordBankList[category];
  const randomIndex = Math.floor(Math.random() * categorySet.length);
  return categorySet[randomIndex];
}

export function getRandomWordCategory() {
  const randomIndex = Math.floor(Math.random() * wordCategories.length);
  return wordCategories[randomIndex];
}

export function getRandomImageFromArray() {
  const randomIndex = Math.floor(Math.random() * images.length);
  return images[randomIndex];
}

export function getSizeOfLongestWord(str) {
  const words = str.split(" ");
  let longestWordLength = 0;
  for (let i = 0; i < words.length; i++) {
    const wordLength = words[i].length;
    if (wordLength > longestWordLength) {
      longestWordLength = wordLength;
    }
  }
  return longestWordLength;
}

export default getRandomWordFromArray;
