var animales = [
  "Perro",
  "Gato",
  "Elefante",
  "León",
  "Tigre",
  "Oso",
  "Mono",
  "Cebra",
  "Jirafa",
  "Caballo",
  "Vaca",
  "Conejo",
  "Lobo",
  "Ratón",
  "Murciélago",
  "Serpiente",
  "Araña",
  "Cocodrilo",
  "Hipopótamo",
  "Delfín",
  "Tortuga",
  "Pingüino",
  "Pato",
  "Gorila",
  "Pez",
  "Avestruz",
  "Camello",
  "Hormiga",
  "Abeja",
  "Colibrí",
];

var sustantivos = [
  "Luz",
  "Mesa",
  "Carro",
  "Llave",
  "Lago",
  "Taza",
  "Pan",
  "Cama",
  "Silla",
  "Puerta",
  "Tierra",
  "Árbol",
  "Nube",
  "Montaña",
  "Bosque",
  "Lápiz",
  "Banco",
  "Camino",
  "Flor",
  "Libro",
  "Río",
  "Reloj",
  "Mango",
  "Naranja",
  "Limon",
  "Nieve",
  "Sauce",
  "Madera",
  "Oro",
  "Plata",
  "Cobre",
  "Hierro",
  "Cielo",
  "Estrella",
  "Mariposa",
  "Caramelo",
  "Helado",
  "Abuela",
  "Pantalón",
  "Camisa",
  "Botella",
];

var musicos = [
  "Mozart",
  "Beethoven",
  "Bach",
  "Chopin",
  "Louis Armstrong",
  "Billie Holiday",
  "Ella Fitzgerald",
  "Nina Simone",
  "Aretha Franklin",
  "Bob Marley",
  "Jimi Hendrix",
  "Janis Joplin",
  "David Bowie",
  "Prince",
  "Stevie Ray Vaughan",
  "Ray Charles",
  "B.B. King",
  "John Coltrane",
  "Miles Davis",
  "Nirvana",
  "Radiohead",
  "Bob Dylan",
  "Leonard Cohen",
  "Nick Cave",
  "Tom Waits",
  "Jeff Buckley",
  "Elliott Smith",
  "Amy Winehouse",
  "Bon Iver",
  "Sufjan Stevens",
  "Tame Impala",
];

var peliculas = [
  "El Padrino",
  "Pulp Fiction",
  "El Señor de los Anillos",
  "El Caballero de la Noche",
  "La Lista de Schindler",
  "El Bueno, el Malo y el Feo",
  "Forrest Gump",
  "Origen",
  "El Club de la Pelea",
  "Ciudadano Kane",
  "El Resplandor",
  "Matrix",
  "Titanic",
  "Interestelar",
  "La Vida es Bella",
  "Gladiador",
  "La Naranja Mecánica",
  "El Silencio de los Inocentes",
  "El Gran Dictador",
  "El Laberinto del Fauno",
  "El Hombre Araña",
  "Star Wars",
  "Volver al Futuro",
  "El Rey León",
  "Los Siete Magníficos",
  "El Exorcista",
  "El Discurso del Rey",
  "El Viaje de Chihiro",
  "La Bella y la Bestia",
  "El Secreto de sus Ojos",
  "El Cisne Negro",
  "La Princesa Mononoke",
  "El Último Tango en París",
  "El Pianista",
  "Psicosis",
  "La La Land",
  "El Código Da Vinci",
  "El Sexto Sentido",
  "Jurassic Park",
  "El Club de los Poetas Muertos",
  "El Hombre Bicentenario",
  "El Mago de Oz",
  "El Cazador de Sueños",
  "El Buen Mentiroso",
  "El Lado Bueno de las Cosas",
  "El Origen del Planeta de los Simios",
  "El Último Samurai",
  "El Gran Hotel Budapest",
  "El Castillo Ambulante",
  "El Gran Gatsby",
  "El Juego de la Imitación",
  "El Informante",
];

var sentimientos = [
  "Alegría",
  "Tristeza",
  "Amor",
  "Odio",
  "Felicidad",
  "Miedo",
  "Esperanza",
  "Ira",
  "Culpabilidad",
  "Enojo",
  "Dolor",
  "Emoción",
  "Sorpresa",
  "Euforia",
  "Nostalgia",
  "Satisfacción",
  "Vergüenza",
  "Envidia",
  "Asco",
  "Confusión",
  "Gratitud",
  "Inseguridad",
  "Preocupación",
  "Aversión",
  "Empatía",
  "Cariño",
  "Paz",
  "Sosiego",
  "Admiración",
  "Culpa",
  "Esperanza",
];

var adjetivos = [
  "Alegre",
  "Triste",
  "Amoroso",
  "Odioso",
  "Feliz",
  "Aterrado",
  "Esperanzado",
  "Irritado",
  "Culpable",
  "Enojado",
  "Doloroso",
  "Emocionante",
  "Sorprendente",
  "Eufórico",
  "Nostálgico",
  "Satisfecho",
  "Vergonzoso",
  "Envidioso",
  "Asqueroso",
  "Confuso",
  "Agradecido",
  "Inseguro",
  "Preocupado",
  "Aversivo",
  "Empático",
  "Cariñoso",
  "Pacífico",
  "Tranquilo",
  "Admirable",
  "Culpable",
  "Esperanzado",
];

var palabrasCion = [
  "Acción",
  "Reacción",
  "Adopción",
  "Corrupción",
  "Educación",
  "Inspiración",
  "Conversación",
  "Obligación",
  "Investigación",
  "Colaboración",
  "Producción",
  "Dirección",
  "Expansión",
  "Preservación",
  "Evaluación",
  "Reflexión",
  "Innovación",
  "Transición",
  "Declaración",
  "Negociación",
];

const wordBankList = [
  musicos,
  adjetivos,
  animales,
  palabrasCion,
  sustantivos,
  sustantivos,
  sentimientos,
  peliculas,
  sustantivos,
  animales,
  sustantivos,
  adjetivos,
  sentimientos,
  palabrasCion,
  sentimientos,
];

export function getRandomWordFromArray() {
  const randomSet =
    wordBankList[Math.floor(Math.random() * wordBankList.length)];
  const randomIndex = Math.floor(Math.random() * randomSet.length);
  return randomSet[randomIndex];
}

export default getRandomWordFromArray;
